apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-prod
  namespace: certmanager
spec:
  acme:
    email: sebastien.villanueva@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: sebastien.villanueva@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-token-secret
            key: api-token