apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus
  name: traefik-ingress
spec:
  endpoints:
    - port: metrics
      scheme: http

  jobLabel: traefik-ingress
  namespaceSelector:
    matchNames:
    - traefik
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik