apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: back1-svc-mon
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: http
  selector:
    matchExpressions:
    - { key: app, operator: In, values: [back1,back1-canary] }
    #matchLabels:
    #  app: back1
