apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1-nginx
  name: app1-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "101"
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: app1-nginx
  type: ClusterIP
status:
  loadBalancer: {}
